# Project information
site_name: ReDeathmatch
site_url: https://wopox1337.github.io/ReDeathmatch/
site_author: Sergey Shorokhov
site_description: >-
  Enables deathmatch style (CSDM) gameplay in Counter-Strike 1.6 (respawning, gun selection, spawn protection, etc).

# Repository
repo_url: https://github.com/wopox1337/ReDeathmatch
repo_name: wopox1337/ReDeathmatch

# Copyright
copyright: Copyright &copy; 2022 - 2023 Sergey Shorokhov

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Montserrat
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - header.autohide
    - content.action.edit
    - content.action.view
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/solid/gun
  

plugins:
  - blog
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes